-- Откат 0001_enable-rls-subsidiary
DROP POLICY "tenant_isolation" ON "subsidiary";
ALTER TABLE "subsidiary" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE "subsidiary" DISABLE ROW LEVEL SECURITY;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM app;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM app;
REVOKE USAGE ON SCHEMA public FROM app;
DROP ROLE IF EXISTS app;
